"""Writing Lua: plain tables for small data, packed strings for large.

A plain Lua table costs tens of bytes per entry once loaded; the spell tables
would take about 37 MB that way against 5 MB on disk. A packed table is one
string of fixed-width decimal records sorted by their first field, which the
addon searches by halving. It costs its own length in memory and stays
readable in an editor.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence

HEADER = "-- Generated by generator/build.py from the client's tables. Do not edit.\n"

Plain = int | str | bool | Sequence["Plain"] | Mapping[int, "Plain"]


def plain(value: Plain) -> str:
    """A value as a Lua literal.

    A named tuple becomes a record keyed by its field names, so the addon reads
    a row by name and a reordered field cannot silently swap two values. Any
    other sequence becomes an array, and a mapping a table keyed by number.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    if isinstance(value, Mapping):
        return "{" + ",".join(f"[{key}]={plain(item)}" for key, item in value.items()) + "}"
    fields: Sequence[str] | None = getattr(value, "_fields", None)
    if fields is not None:
        pairs = zip(fields, value, strict=True)
        return "{" + ",".join(f"{name}={plain(item)}" for name, item in pairs) + "}"
    return "{" + ",".join(plain(item) for item in value) + "}"


def keyed(entries: Mapping[str, int]) -> str:
    """Names and numbers as one string, `;name=number;` after another, for finding by name.

    A name is found by searching for `;name=`, which a string search does in one
    pass, and a string costs its own length in memory where a table of the same
    entries costs several times more. Raises `ValueError` for a name holding
    either separator, which would make a search find the wrong entry.
    """
    for name in entries:
        if ";" in name or "=" in name:
            raise ValueError(f"{name!r} holds a separator")
    return plain(";" + "".join(f"{name}={number};" for name, number in sorted(entries.items())))


def packed(
    rows: Iterable[Sequence[int]], widths: Sequence[int], offsets: Sequence[int] | None = None
) -> str:
    """Rows of integers as one string of fixed-width decimal records.

    Rows are written in ascending order, so a reader can search on the leading
    fields. Each field is stored with its offset added, which is how a field
    whose smallest value is negative is kept non-negative. Raises `ValueError`
    when a stored value is negative or does not fit its width: a silently
    truncated id would preview the wrong thing.
    """
    shifts = list(offsets) if offsets is not None else [0] * len(widths)
    out = []
    for row in sorted(tuple(row) for row in rows):
        if len(row) != len(widths):
            raise ValueError(f"row {row!r} does not have {len(widths)} fields")
        for value, width, shift in zip(row, widths, shifts, strict=True):
            stored = value + shift
            if stored < 0 or stored >= 10**width:
                raise ValueError(f"{value} in row {row!r} does not fit {width} digits")
            out.append(f"{stored:0{width}d}")
    return "".join(out)


def packed_table(
    rows: Iterable[Sequence[int]], widths: Sequence[int], offsets: Sequence[int] | None = None
) -> str:
    """A packed table as the Lua literal the addon reads: widths, offsets and records."""
    shifts = list(offsets) if offsets is not None else [0] * len(widths)
    records = plain(packed(rows, widths, shifts))
    return f"{{widths={plain(list(widths))},offsets={plain(shifts)},records={records}}}"
